/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */


plugins {
    java
    application
    id("com.github.ben-manes.versions") version "0.51.0"
}



repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-java
    testImplementation("org.seleniumhq.selenium:selenium-java:4.35.0")
    testImplementation("commons-io:commons-io:2.20.0")
    testImplementation("com.github.javafaker:javafaker:1.0.2")

    testImplementation("io.cucumber:cucumber-java:7.27.2")
    testImplementation("io.cucumber:cucumber-junit-platform-engine:7.27.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
    testImplementation("org.junit.platform:junit-platform-suite:1.13.4")
    //testImplementation("io.cucumber:cucumber-java:7.27.2")
    //testImplementation("io.cucumber:cucumber-junit:7.27.2")
    testImplementation("com.fasterxml.jackson.core:jackson-databind:2.19.2")
    testImplementation("org.jsoup:jsoup:1.21.2")


    // Use JUnit Jupiter for testing.
    //testImplementation(libs.junit.jupiter)

    //testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    //implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "java.App"
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}

